config/routes.rb
Blog::Application.routes.draw do
  
  
  resources :sub_categories

  resources :categories do
    collection do
      get :sub_categories
    end
  end

  resources :authors do
    collection do
      get :categories
    end
  end

  resources :messages
  root :to => 'messages#index'

end

app/models/author.rb
class Author < ActiveRecord::Base

  default_scope order("authors.name")
  has_many :messages, :dependent => :destroy

  validates :name,
    :presence => true

  validates :email,
    :presence => true,
    :uniqueness => true

  validates :phone,
    :presence => true
    

  delegate :size, :to => :messages, :prefix => true
  self.per_page = 10
  
# Agrego imagen.
   has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  def has_image?
    self.image.attachment_file_name ? true : false rescue false
#    (!self.image.blank?||self.image.file?) rescue false
  end

  def categories
    self.messages.map(&:category).
      compact. # Saco los nil
      uniq. # No repite
      sort_by(&:name) rescue []
  end  
  
  def sub_categories category_id
    self.categories.detect{|category| category_id.to_i == category.id}. # Traigo la categoria actual
    sub_categories. # Sub categorias
    flatten. # Junto los sub-arrays
    compact.uniq.reject{|sub_category| sub_category.blank?}.sort_by(&:name) rescue []
  end
  
  def self.search query, page
    where("authors.name LIKE :query OR authors.email LIKE :query" ,:query => "%#{query}%").paginate(:page => page)
  end

  def image_url(style=:large)
    self.image.url(style) rescue nil
  end

  def thumb
    image_url(:thumb)
  end

  def small
    image_url(:small)
  end

  def large
    image_url(:large)
  end

  def flash_thumb
    image_url(:flash_thumb)
  end
end

app/models/author/image.rb
class Author::Image < Attachment
  has_attached_file :attachment,
    :url => "/system/:class/:attachment/:id_partition/:style/:id.:extension",
    :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:id.:extension",
    :styles => {:large => "188x188",
    :small => "115x95", :thumb => "16x16"},
    :default_url => APP_CONFIG["urlserver"] + "/images/no_image.png"
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def create
      if new_author.save
        redirect_to new_author, :notice => 'Author was successfully created.'
      else
        render :action => "new" 
      end
  end
  
  def update
   
      if author.update_attributes(params[:author])
       redirect_to author, :notice => 'Author was successfully updated.'
      else
       render :action => "edit" 
      end
  end
    
  def destroy
    author.destroy
    redirect_to authors_url
  end
  
  def categories
    render :layout => false
  end
# Instancias
  def author
  @author ||= Author.find(params[:id]) rescue nil
  end
  helper_method :author
  
  def author_categories
    @author_categories ||= author.categories rescue []
  end
  helper_method :author_categories
  
  def authors
  @authors ||= Author.search(params[:query], params[:page])
  end
  helper_method :authors
  
  def new_author
  @new_author ||= Author.new(params[:author])
  end
  helper_method :new_author
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
 <tr>
    <td><%= author.name %></td>
    <td><%= author.messages_size %></td>
    <td><%= author.email %></td>
    <td><%= author.phone %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

app/views/authors/_form.html.erb
<%= form_for(author, :html => { :multipart => true } ) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div>
   <%= image_tag author.image.url(:medium) if author.image %>
  </div>
  <div>  
  <%= f.label :image %>
  <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/authors/categories.html.erb
<%= select :message, :category_id, options_from_collection_for_select(author_categories, :id, :name), :include_blank => true %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>
<%= form_for :search, :url => authors_path, :html => {:method => :get} do %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search", :name => nil %>
<% end %>
<table>
  <tr>
    <th>Name</th>
    <th>Messages</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= render authors %>
</table>
<%= will_paginate authors %>
<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form', :author => new_author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= author.name %>
</p>

<p>
  <b>Email:</b>
  <%= author.email %>
</p>

<p>
  <b>Phone:</b>
  <%= author.phone %>
</p>
<p>
  <b>Avatar:</b>
  <%= image_tag author.image.url(:medium) if author.image %>
</p>


<%= link_to 'Edit', edit_author_path(author) %> |
<%= link_to 'Back', authors_path %>