config/routes.rb
Blog::Application.routes.draw do
  
  
  resources :sub_categories

  resources :categories do
    collection do
      get :sub_categories
    end
  end

  resources :authors do
    collection do
      get :categories
    end
  end

  resources :messages
  root :to => 'messages#index'

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  default_scope order("sub_categories.name")
  scope :with_a, where("title LIKE ?", "%a%")
  belongs_to :category
  has_many :messages
  
   validates :name,
  :presence => true,
  :uniqueness => true
  
  self.per_page = 10
   def self.search query, page
  where("sub_categories.name LIKE :query",:query => "%#{query}%").paginate(:page => page)
  end
  
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController

  def create
      if new_sub_category.save
       redirect_to new_sub_category, :notice => 'Sub category was successfully created.' 
      else
       render :action => "new"       
      end
  end

  def update
      if sub_category.update_attributes(params[:sub_category])
       redirect_to sub_category, :notice => 'Sub category was successfully updated.' 
      else
        render :action => "edit"
      end
  end

  def destroy
   sub_category.destroy
   redirect_to sub_categories_url 
  end
  
# Instances
  def categories
  @categories ||= Category.all
  end
  helper_method :categories
  
  def category_id
  (params[:category]||{})[:category_id]
  end
  helper_method :category_id
      
  def new_sub_category
  @new_sub_category ||= SubCategory.new(params[:sub_category])
  end
  helper_method :new_sub_category  
  
  def sub_categories
  @sub_categories ||= SubCategory.search(params[:query], params[:page])
  end
  helper_method :sub_categories
  
  def sub_category
  @sub_category ||= SubCategory.find(params[:id])
  end
  helper_method :sub_category
     
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for(sub_category) do |f| %>
  <% if sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% sub_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, categories, :id, :name, :include_blank => true  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/_sub_category.html.erb
  <tr>
    <td><%= sub_category.name %></td>
    <td><%= sub_category.category_id %></td>
    <td><%= link_to 'Show', sub_category %></td>
    <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
    <td><%= link_to 'Destroy', sub_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>

app/views/sub_categories/edit.html.erb
<h1>Editing sub_category</h1>

<%= render 'form' %>

<%= link_to 'Show', sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<h1>Listing sub_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render sub_categories %>
</table>

<br />

<%= link_to 'New Sub category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New sub_category</h1>

<%= render 'form', :sub_category => new_sub_category %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= sub_category.name %>
</p>

<p>
  <b>Category:</b>
  <%= sub_category.category_id %>
</p>


<%= link_to 'Edit', edit_sub_category_path(sub_category) %> |
<%= link_to 'Back', sub_categories_path %>